image: debian:buster

pages:
  script:
  - apt-get update && apt-get -y install rsync make python3 python3-setuptools nodejs npm git
  - make build
  - rsync -a build/lib/notebook/ public/
  artifacts:
    paths:
    - public/
