image: debian:buster

pages:
  script:
  - apt-get update && apt-get -y install make python3 python3-setuptools python3-pip nodejs npm git
  - make build
  - mv build/lib/notebook public
  artifacts:
    paths:
    - public/
