image: debian:buster

pages:
  script:
  - apt-get update && apt-get -y install make python3 python3-setuptools nodejs npm git pip3
  - pip3 install basthon-kernel
  - make build
  - mv build/lib/notebook public
  artifacts:
    paths:
    - public/
